# Generated by Django 3.1.3 on 2020-11-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=512, null=True)),
                ('id_user', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
